language: generic
matrix:
   include:
      # Test Ubuntu Linux 14.04 / Swift 4.1.2
       - os: linux
         dist: trusty
         sudo: required
      # Test Xcode 9.3 / Swift 4.1.0
       - os: osx
         osx_image: xcode9.3
      # Test Xcode 9.4.1 / Swift 4.1.2
       - os: osx
         osx_image: xcode9.4
      # Test Xcode 10 / Swift 4.2
       - os: osx
         osx_image: xcode10
      # Test Xcode 10.2 / Swift 5
       - os: osx
         osx_image: xcode10.2

addons:
  apt:
    packages:
    - clang
    - pkg-config
install:
  # Install Swift 4.1.2 on Ubuntu Linux 14.04
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then SWIFT_DIR=tests ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir $SWIFT_DIR ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://swift.org/builds/swift-4.1.2-release/ubuntu1404/swift-4.1.2-RELEASE/swift-4.1.2-RELEASE-ubuntu14.04.tar.gz -s | tar xz -C $SWIFT_DIR &> /dev/null ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install clang ; fi
env:
  - SWIFT_VERSION=swift-4.1.2-RELEASE
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$(pwd)/tests/$SWIFT_VERSION-ubuntu14.04/usr/bin:"${PATH}" ; fi
  # Compile with SPM
  - swift test
  # Compile with Xcode
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd Xcode ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild clean test -scheme TLVCoding-macOS ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild clean build -scheme TLVCoding-iOS ; fi
