name: Documentation

on:
  workflow_dispatch:
  release:

jobs:
# Create documentation
    docs:
        name: Documentation
        runs-on: macOS-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Xcode Version
          run: |
            xcodebuild -version
            swift --version
        - name: Swift Version
          run: swift --version
        - name: Generate documentation
          uses: sersoft-gmbh/swifty-docs-action@v1
        - name: Upload docs
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: docs
            path: docs
