name: Release

on:
  release:

jobs:
# Build XCFramework
  xcframework:
    name: XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_12.app
           xcodebuild -version
           swift --version
      - name: Swift Version
        run: swift --version
      # Create a release
      - name: Install Mint
        run: brew install mint
      - name: Install swift-create-xcframework
        run: mint install unsignedapps/swift-create-xcframework
      - name: Build XCFramework
        run: swift-create-xcframework
      # Upload build artifacts
      - name: Upload xcframework
        uses: actions/upload-artifact@v2
        with:
          name: xcframework
          path: "./*.xcframework"

  linux-swift-armv7:
        name: Linux ARMv7
        runs-on: [self-hosted, linux, arm]
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Swift Version
          run: swift --version
        - name: Build (Release)
          run: swift build -j 1 -c release
        # Upload build artifacts
        - name: Upload build artifacts
          uses: actions/upload-artifact@v2
          with:
            name: build-linux-armv7
            path: "./.build/armv7*/release/*.so"
