name: Swift ARM

on:
  push:
    branches: [ master ]

jobs:

    linux-swift-armv7:
        name: Linux ARMv7
        runs-on: [self-hosted, linux, arm]
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Swift Version
          run: swift --version
        - name: Build (Debug)
          run: swift build -j 1 -c debug
        - name: Test (Debug)
          run: swift test -j 1 --configuration debug
        - name: Test (Release)
          run: swift test -j 1 --configuration release -Xswiftc -enable-testing
        - name: Clean
          run: rm -rf .build
        - name: Build (Release)
          run: swift build -j 1 -c release
        - name: Upload build artifacts
          uses: actions/upload-artifact@v2
          with:
            name: build-linux-armv7
            path: "./.build/armv7*/release/*.so"
