name: Xcode

on: [push]

jobs:

    xcode-swift-52:
        name: Xcode (Swift 5.2)
        runs-on: macOS-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Make Logs Directory
          run: mkdir logs
        - name: Xcode Version
          run: |
            sudo xcode-select -s /Applications/Xcode_11.4.app
            xcodebuild -version
            swift --version
        - name: XC Pretty
          run: sudo gem install xcpretty-travis-formatter
        - name: Detect Workspace & Scheme (macOS)
          run: |
            WORKSPACE="TLVCoding.xcworkspace"
            if [[ ! -e "$WORKSPACE" ]]
            then
            WORKSPACE="."
            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep TLVCoding-Package || true))
            if [[ $GOTPACKAGE != "" ]]
            then
            SCHEME="TLVCoding-Package"
            else
            SCHEME="TLVCoding"
            fi
            else
            SCHEME="TLVCoding-macOS"
            fi
            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
        - name: Build (macOS Debug)
          run: |
            source "setup.sh"
            echo "Building workspace $WORKSPACE scheme $SCHEME."
            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-xcode-build-debug.log | xcpretty
        - name: Detect Workspace & Scheme (iOS)
          run: |
            WORKSPACE="TLVCoding.xcworkspace"
            if [[ ! -e "$WORKSPACE" ]]
            then
            WORKSPACE="."
            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep TLVCoding-Package || true))
            if [[ $GOTPACKAGE != "" ]]
            then
            SCHEME="TLVCoding-Package"
            else
            SCHEME="TLVCoding"
            fi
            else
            SCHEME="TLVCoding-iOS"
            fi
            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
        - name: Build (iOS Debug)
          run: |
            source "setup.sh"
            echo "Building workspace $WORKSPACE scheme $SCHEME."
            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-debug.log | xcpretty
        - name: Detect Workspace & Scheme (tvOS)
          run: |
            WORKSPACE="TLVCoding.xcworkspace"
            if [[ ! -e "$WORKSPACE" ]]
            then
            WORKSPACE="."
            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep TLVCoding-Package || true))
            if [[ $GOTPACKAGE != "" ]]
            then
            SCHEME="TLVCoding-Package"
            else
            SCHEME="TLVCoding"
            fi
            else
            SCHEME="TLVCoding-tvOS"
            fi
            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
        - name: Build (tvOS Debug)
          run: |
            source "setup.sh"
            echo "Building workspace $WORKSPACE scheme $SCHEME."
            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-debug.log | xcpretty
        - name: Detect Workspace & Scheme (watchOS)
          run: |
            WORKSPACE="TLVCoding.xcworkspace"
            if [[ ! -e "$WORKSPACE" ]]
            then
            WORKSPACE="."
            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep TLVCoding-Package || true))
            if [[ $GOTPACKAGE != "" ]]
            then
            SCHEME="TLVCoding-Package"
            else
            SCHEME="TLVCoding"
            fi
            else
            SCHEME="TLVCoding-watchOS"
            fi
            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
        - name: Build (watchOS Debug)
          run: |
            source "setup.sh"
            echo "Building workspace $WORKSPACE scheme $SCHEME."
            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-watchOS-build-debug.log | xcpretty
        - name: Upload Logs
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: logs

    xcode-swift-53:
        name: Xcode (Swift 5.3)
        runs-on: macOS-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Make Logs Directory
          run: mkdir logs
        - name: Xcode Version
          run: |
            sudo xcode-select -s /Applications/Xcode_12.app
            xcodebuild -version
            swift --version
        - name: XC Pretty
          run: sudo gem install xcpretty-travis-formatter
        - name: Detect Workspace & Scheme (macOS)
          run: |
            WORKSPACE="TLVCoding.xcworkspace"
            if [[ ! -e "$WORKSPACE" ]]
            then
            WORKSPACE="."
            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep TLVCoding-Package || true))
            if [[ $GOTPACKAGE != "" ]]
            then
            SCHEME="TLVCoding-Package"
            else
            SCHEME="TLVCoding"
            fi
            else
            SCHEME="TLVCoding-macOS"
            fi
            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
        - name: Build (macOS Debug)
          run: |
            source "setup.sh"
            echo "Building workspace $WORKSPACE scheme $SCHEME."
            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-xcode-build-debug.log | xcpretty
        - name: Detect Workspace & Scheme (iOS)
          run: |
            WORKSPACE="TLVCoding.xcworkspace"
            if [[ ! -e "$WORKSPACE" ]]
            then
            WORKSPACE="."
            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep TLVCoding-Package || true))
            if [[ $GOTPACKAGE != "" ]]
            then
            SCHEME="TLVCoding-Package"
            else
            SCHEME="TLVCoding"
            fi
            else
            SCHEME="TLVCoding-iOS"
            fi
            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
        - name: Build (iOS Debug)
          run: |
            source "setup.sh"
            echo "Building workspace $WORKSPACE scheme $SCHEME."
            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-debug.log | xcpretty
        - name: Detect Workspace & Scheme (tvOS)
          run: |
            WORKSPACE="TLVCoding.xcworkspace"
            if [[ ! -e "$WORKSPACE" ]]
            then
            WORKSPACE="."
            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep TLVCoding-Package || true))
            if [[ $GOTPACKAGE != "" ]]
            then
            SCHEME="TLVCoding-Package"
            else
            SCHEME="TLVCoding"
            fi
            else
            SCHEME="TLVCoding-tvOS"
            fi
            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
        - name: Build (tvOS Debug)
          run: |
            source "setup.sh"
            echo "Building workspace $WORKSPACE scheme $SCHEME."
            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-debug.log | xcpretty
        - name: Detect Workspace & Scheme (watchOS)
          run: |
            WORKSPACE="TLVCoding.xcworkspace"
            if [[ ! -e "$WORKSPACE" ]]
            then
            WORKSPACE="."
            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep TLVCoding-Package || true))
            if [[ $GOTPACKAGE != "" ]]
            then
            SCHEME="TLVCoding-Package"
            else
            SCHEME="TLVCoding"
            fi
            else
            SCHEME="TLVCoding-watchOS"
            fi
            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
        - name: Build (watchOS Debug)
          run: |
            source "setup.sh"
            echo "Building workspace $WORKSPACE scheme $SCHEME."
            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-watchOS-build-debug.log | xcpretty
